// بيانات المشروع - يمكن إضافة مراحل جديدة هنا لاحقًا (انظر ملف README)
const SITE_DATA = {
  stages: {
    stage0: {
      id: "stage0",
      name: "المرحلة التمهيدية",
      subjects: [
        { key: "muqaddimat", name: "مقدمات تمهيدية", sheikh: "أحمد السيد", tags: ["مقدمات_تمهيدية"], lectures: [
          { id: "stage0_muqaddimat_01", n: 1, day: 1, title: "فتعلمنا الإيمان", file: "lectures/01.html", video: "kAilDgzTOiI" },
          { id: "stage0_muqaddimat_02", n: 2, day: 2, title: "القلب المنيب", file: "lectures/02.html", video: "qyyaKtVeW9w" }
        ]},
        { key: "madkhal-manhaj", name: "المدخل إلى المنهاج", sheikh: "أحمد السيد", tags: ["المنهاج"], lectures: [
          { id: "stage0_madkhal-manhaj_01", n: 1, day: 3, title: "المدخل إلى المنهاج", file: "lectures/01.html", video: "TwcAyIFb3Bg" }
        ]},
        { key: "qabas-wahhaj", name: "القبس الوهاج (مختصر شرح المنهاج)", sheikh: "محمد شميس", tags: ["المنهاج"], lectures: [
          { id: "stage0_qabas-wahhaj_01", n: 1, day: 4, title: "القبس الوهاج — من ص 7 إلى 27", file: "lectures/01.html" },
          { id: "stage0_qabas-wahhaj_02", n: 2, day: 5, title: "القبس الوهاج — من ص 28 إلى 45", file: "lectures/02.html" },
          { id: "stage0_qabas-wahhaj_03", n: 3, day: 8, title: "القبس الوهاج — من ص 46 إلى 67", file: "lectures/03.html" },
          { id: "stage0_qabas-wahhaj_04", n: 4, day: 9, title: "القبس الوهاج — من ص 68 إلى 92", file: "lectures/04.html" },
          { id: "stage0_qabas-wahhaj_05", n: 5, day: 11, title: "القبس الوهاج — من ص 93 إلى 111", file: "lectures/05.html" },
          { id: "stage0_qabas-wahhaj_06", n: 6, day: 12, title: "القبس الوهاج — من ص 112 إلى 136", file: "lectures/06.html" },
          { id: "stage0_qabas-wahhaj_07", n: 7, day: 15, title: "القبس الوهاج — من ص 137 إلى 161", file: "lectures/07.html" },
          { id: "stage0_qabas-wahhaj_08", n: 8, day: 16, title: "القبس الوهاج — من ص 162 إلى 181", file: "lectures/08.html" },
          { id: "stage0_qabas-wahhaj_09", n: 9, day: 18, title: "القبس الوهاج — من ص 182 إلى 204", file: "lectures/09.html" },
          { id: "stage0_qabas-wahhaj_10", n: 10, day: 19, title: "القبس الوهاج — من ص 205 إلى 224", file: "lectures/10.html" },
          { id: "stage0_qabas-wahhaj_11", n: 11, day: 22, title: "القبس الوهاج — من ص 225 إلى نهاية الكتاب", file: "lectures/11.html" }
        ]},
        { key: "midarasat", name: "لقاءات مدارسة المنهاج", sheikh: "ميراث النبوة", tags: ["المنهاج", "مدارسة"], lectures: [
          { id: "stage0_midarasat_01", n: 1, day: 6, title: "لقاء مدارسة المنهاج (1)", file: "lectures/01.html", video: "P5h1hsf63u8" },
          { id: "stage0_midarasat_02", n: 2, day: 10, title: "لقاء مدارسة المنهاج (2)", file: "lectures/02.html", video: "3RoGN85lPSw" },
          { id: "stage0_midarasat_03", n: 3, day: 13, title: "لقاء مدارسة المنهاج (3)", file: "lectures/03.html", video: "V546SfV4NmM" },
          { id: "stage0_midarasat_04", n: 4, day: 17, title: "لقاء مدارسة المنهاج (4)", file: "lectures/04.html", video: "sosqs_mnOjE" },
          { id: "stage0_midarasat_05", n: 5, day: 20, title: "لقاء مدارسة المنهاج (5)", file: "lectures/05.html" },
          { id: "stage0_midarasat_06", n: 6, day: 23, title: "لقاء مدارسة المنهاج (6)", file: "lectures/06.html", video: "mZMkyXX45UM" }
        ]},
        { key: "manhajiyyah", name: "العلم بين المنهجية والفوضوية", sheikh: "أحمد السيد", tags: ["منهجية_الطلب"], lectures: [
          { id: "stage0_manhajiyyah_01", n: 1, day: 28, title: "العلم بين المنهجية والفوضوية — النصف الأول", file: "lectures/01.html" },
          { id: "stage0_manhajiyyah_02", n: 2, day: 29, title: "العلم بين المنهجية والفوضوية — النصف الثاني", file: "lectures/02.html" }
        ]},
        { key: "ilm-billah", name: "العلم بالله", sheikh: "أحمد السيد", tags: ["عقيدة"], lectures: [
          { id: "stage0_ilm-billah_01", n: 1, day: 30, title: "العلم بالله — النصف الأول", file: "lectures/01.html" },
          { id: "stage0_ilm-billah_02", n: 2, day: 31, title: "العلم بالله — النصف الثاني", file: "lectures/02.html" }
        ]},
        { key: "tawhid", name: "لا إله إلا الله", sheikh: "أحمد السيد", tags: ["عقيدة"], lectures: [
          { id: "stage0_tawhid_01", n: 1, day: 33, title: "لا إله إلا الله — المحاضرة كاملة", file: "lectures/01.html" }
        ]},
        { key: "bina-aqadi", name: "البناء العقدي", sheikh: "أحمد السيد", tags: ["عقيدة"], lectures: [
          { id: "stage0_bina-aqadi_01", n: 1, day: 34, title: "البناء العقدي — من ص 27 إلى 51", file: "lectures/01.html" },
          { id: "stage0_bina-aqadi_02", n: 2, day: 35, title: "البناء العقدي — من ص 51 إلى 73", file: "lectures/02.html" },
          { id: "stage0_bina-aqadi_03", n: 3, day: 36, title: "البناء العقدي — من ص 75 إلى 96", file: "lectures/03.html" },
          { id: "stage0_bina-aqadi_04", n: 4, day: 37, title: "البناء العقدي — من ص 97 إلى 119", file: "lectures/04.html" },
          { id: "stage0_bina-aqadi_05", n: 5, day: 38, title: "البناء العقدي — من ص 120 إلى 139", file: "lectures/05.html" },
          { id: "stage0_bina-aqadi_06", n: 6, day: 39, title: "البناء العقدي — من ص 139 إلى نهاية الكتاب", file: "lectures/06.html" }
        ]}
      ],
      days: [
        { day: 1, kind: "lecture", lectureId: "stage0_muqaddimat_01", subjectKey: "muqaddimat", subjectName: "مقدمات تمهيدية", title: "فتعلمنا الإيمان", link: "muqaddimat/lectures/01.html" },
        { day: 2, kind: "lecture", lectureId: "stage0_muqaddimat_02", subjectKey: "muqaddimat", subjectName: "مقدمات تمهيدية", title: "القلب المنيب", link: "muqaddimat/lectures/02.html" },
        { day: 3, kind: "lecture", lectureId: "stage0_madkhal-manhaj_01", subjectKey: "madkhal-manhaj", subjectName: "المدخل إلى المنهاج", title: "المدخل إلى المنهاج", link: "madkhal-manhaj/lectures/01.html" },
        { day: 4, kind: "lecture", lectureId: "stage0_qabas-wahhaj_01", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 7 إلى 27", link: "qabas-wahhaj/lectures/01.html" },
        { day: 5, kind: "lecture", lectureId: "stage0_qabas-wahhaj_02", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 28 إلى 45", link: "qabas-wahhaj/lectures/02.html" },
        { day: 6, kind: "lecture", lectureId: "stage0_midarasat_01", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (1)", link: "midarasat/lectures/01.html" },
        { day: 7, kind: "rest", id: "stage0_rest_07", title: "استدراك وراحة" },
        { day: 8, kind: "lecture", lectureId: "stage0_qabas-wahhaj_03", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 46 إلى 67", link: "qabas-wahhaj/lectures/03.html" },
        { day: 9, kind: "lecture", lectureId: "stage0_qabas-wahhaj_04", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 68 إلى 92", link: "qabas-wahhaj/lectures/04.html" },
        { day: 10, kind: "lecture", lectureId: "stage0_midarasat_02", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (2)", link: "midarasat/lectures/02.html" },
        { day: 11, kind: "lecture", lectureId: "stage0_qabas-wahhaj_05", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 93 إلى 111", link: "qabas-wahhaj/lectures/05.html" },
        { day: 12, kind: "lecture", lectureId: "stage0_qabas-wahhaj_06", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 112 إلى 136", link: "qabas-wahhaj/lectures/06.html" },
        { day: 13, kind: "lecture", lectureId: "stage0_midarasat_03", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (3)", link: "midarasat/lectures/03.html" },
        { day: 14, kind: "rest", id: "stage0_rest_14", title: "استدراك وراحة" },
        { day: 15, kind: "lecture", lectureId: "stage0_qabas-wahhaj_07", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 137 إلى 161", link: "qabas-wahhaj/lectures/07.html" },
        { day: 16, kind: "lecture", lectureId: "stage0_qabas-wahhaj_08", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 162 إلى 181", link: "qabas-wahhaj/lectures/08.html" },
        { day: 17, kind: "lecture", lectureId: "stage0_midarasat_04", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (4)", link: "midarasat/lectures/04.html" },
        { day: 18, kind: "lecture", lectureId: "stage0_qabas-wahhaj_09", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 182 إلى 204", link: "qabas-wahhaj/lectures/09.html" },
        { day: 19, kind: "lecture", lectureId: "stage0_qabas-wahhaj_10", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 205 إلى 224", link: "qabas-wahhaj/lectures/10.html" },
        { day: 20, kind: "lecture", lectureId: "stage0_midarasat_05", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (5)", link: "midarasat/lectures/05.html" },
        { day: 21, kind: "rest", id: "stage0_rest_21", title: "استدراك وراحة" },
        { day: 22, kind: "lecture", lectureId: "stage0_qabas-wahhaj_11", subjectKey: "qabas-wahhaj", subjectName: "القبس الوهاج (مختصر شرح المنهاج)", title: "القبس الوهاج — من ص 225 إلى نهاية الكتاب", link: "qabas-wahhaj/lectures/11.html" },
        { day: 23, kind: "lecture", lectureId: "stage0_midarasat_06", subjectKey: "midarasat", subjectName: "لقاءات مدارسة المنهاج", title: "لقاء مدارسة المنهاج (6)", link: "midarasat/lectures/06.html" },
        { day: 24, kind: "rest", id: "stage0_rest_24", title: "استدراك وراحة" },
        { day: 25, kind: "rest", id: "stage0_rest_25", title: "استدراك وراحة" },
        { day: 26, kind: "exam", id: "stage0_exam_26", title: "الامتحان الأول على النصف الأول من المرحلة التمهيدية" },
        { day: 27, kind: "exam", id: "stage0_exam_27", title: "الامتحان الثاني على النصف الأول من المرحلة التمهيدية" },
        { day: 28, kind: "lecture", lectureId: "stage0_manhajiyyah_01", subjectKey: "manhajiyyah", subjectName: "العلم بين المنهجية والفوضوية", title: "العلم بين المنهجية والفوضوية — النصف الأول", link: "manhajiyyah/lectures/01.html" },
        { day: 29, kind: "lecture", lectureId: "stage0_manhajiyyah_02", subjectKey: "manhajiyyah", subjectName: "العلم بين المنهجية والفوضوية", title: "العلم بين المنهجية والفوضوية — النصف الثاني", link: "manhajiyyah/lectures/02.html" },
        { day: 30, kind: "lecture", lectureId: "stage0_ilm-billah_01", subjectKey: "ilm-billah", subjectName: "العلم بالله", title: "العلم بالله — النصف الأول", link: "ilm-billah/lectures/01.html" },
        { day: 31, kind: "lecture", lectureId: "stage0_ilm-billah_02", subjectKey: "ilm-billah", subjectName: "العلم بالله", title: "العلم بالله — النصف الثاني", link: "ilm-billah/lectures/02.html" },
        { day: 32, kind: "rest", id: "stage0_rest_32", title: "استدراك وراحة" },
        { day: 33, kind: "lecture", lectureId: "stage0_tawhid_01", subjectKey: "tawhid", subjectName: "لا إله إلا الله", title: "لا إله إلا الله — المحاضرة كاملة", link: "tawhid/lectures/01.html" },
        { day: 34, kind: "lecture", lectureId: "stage0_bina-aqadi_01", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 27 إلى 51", link: "bina-aqadi/lectures/01.html" },
        { day: 35, kind: "lecture", lectureId: "stage0_bina-aqadi_02", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 51 إلى 73", link: "bina-aqadi/lectures/02.html" },
        { day: 36, kind: "lecture", lectureId: "stage0_bina-aqadi_03", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 75 إلى 96", link: "bina-aqadi/lectures/03.html" },
        { day: 37, kind: "lecture", lectureId: "stage0_bina-aqadi_04", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 97 إلى 119", link: "bina-aqadi/lectures/04.html" },
        { day: 38, kind: "lecture", lectureId: "stage0_bina-aqadi_05", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 120 إلى 139", link: "bina-aqadi/lectures/05.html" },
        { day: 39, kind: "lecture", lectureId: "stage0_bina-aqadi_06", subjectKey: "bina-aqadi", subjectName: "البناء العقدي", title: "البناء العقدي — من ص 139 إلى نهاية الكتاب", link: "bina-aqadi/lectures/06.html" },
        { day: 40, kind: "rest", id: "stage0_rest_40", title: "استدراك وراحة" },
        { day: 41, kind: "rest", id: "stage0_rest_41", title: "استدراك وراحة" },
        { day: 42, kind: "rest", id: "stage0_rest_42", title: "استدراك وراحة" },
        { day: 43, kind: "exam", id: "stage0_exam_43", title: "الامتحان الأول على النصف الثاني من المرحلة التمهيدية" },
        { day: 44, kind: "exam", id: "stage0_exam_44", title: "الامتحان الثاني على النصف الثاني من المرحلة التمهيدية" },
        { day: 45, kind: "exam", id: "stage0_exam_45", title: "الامتحان النهائي على المرحلة التمهيدية" }
      ],
      totalLectures: 31
    },
    
    stage1: {
      id: "stage1",
      name: "المرحلة الأولى",
      subjects: [
        { key: "nahw", name: "مدخل إلى علم النحو", sheikh: "سالم القحطاني", tags: ["مداخل_العلوم"], lectures: [
          { id: "stage1_nahw_01", n: 1, day: 1, title: "محاضرة كاملة", file: "lectures/01.html" }
        ]},
        { key: "fiqh", name: "مدخل إلى علم الفقه", sheikh: "عامر بهجت", tags: ["مداخل_العلوم"], lectures: [
          { id: "stage1_fiqh_01", n: 1, day: 2, title: "المحاضرة 1", file: "lectures/01.html" },
          { id: "stage1_fiqh_02", n: 2, day: 3, title: "المحاضرة 2", file: "lectures/02.html" },
          { id: "stage1_fiqh_05", n: 3, day: 8, title: "المحاضرة 3", file: "lectures/05.html" },
          { id: "stage1_fiqh_06", n: 4, day: 9, title: "المحاضرة 4", file: "lectures/06.html" },
          { id: "stage1_fiqh_07", n: 5, day: 10, title: "المحاضرة 5", file: "lectures/07.html" },
          { id: "stage1_fiqh_08", n: 6, day: 15, title: "المحاضرة 6", file: "lectures/08.html" },
          { id: "stage1_fiqh_09", n: 7, day: 16, title: "المحاضرة 7", file: "lectures/09.html" }
        ]},
        { key: "hadith", name: "مدخل إلى علم الحديث", sheikh: "أحمد السيد", tags: ["مداخل_العلوم"], lectures: [
          { id: "stage1_hadith_01", n: 1, day: 29, title: "المجلس الأول (1/3)", file: "lectures/01.html?p=stage1_hadith_01" },
          { id: "stage1_hadith_02", n: 2, day: 32, title: "المجلس الأول (2/3)", file: "lectures/01.html?p=stage1_hadith_02" },
          { id: "stage1_hadith_03", n: 3, day: 33, title: "المجلس الأول (3/3)", file: "lectures/01.html?p=stage1_hadith_03" },
          { id: "stage1_hadith_04", n: 4, day: 34, title: "المجلس الثاني (1/2)", file: "lectures/02.html?p=stage1_hadith_04" },
          { id: "stage1_hadith_05", n: 5, day: 39, title: "المجلس الثاني (2/2)", file: "lectures/02.html?p=stage1_hadith_05" }
        ]},
        { key: "quran-sciences", name: "مدخل إلى علوم القرآن", sheikh: "أحمد السيد", tags: ["مداخل_العلوم"], lectures: [
          { id: "stage1_quran-sciences_01_p1", n: 1, day: 17, title: "المدخل إلى علوم القرآن والتفسير — الجزء الأول", file: "lectures/01.html?p=1" },
          { id: "stage1_quran-sciences_01_p2", n: 2, day: 22, title: "المدخل إلى علوم القرآن والتفسير — الجزء الثاني", file: "lectures/01.html?p=2" }
        ]},
        { key: "aqeedah", name: "مدخل إلى علم العقيدة", sheikh: "أحمد السيد", tags: ["مداخل_العلوم"], lectures: [
          { id: "stage1_aqeedah_01", n: 1, day: 23, title: "محاضرة كاملة", file: "lectures/01.html" }
        ]},
        { key: "anwar-al-anbiya", name: "أنوار الأنبياء", sheikh: "أحمد السيد", tags: ["المنهج_الإصلاحي", "التزكية"], lectures: [
          { id: "stage1_anwar-al-anbiya_01", n: 1, day: 4, title: "من بداية الكتاب إلى ص 34", file: "lectures/03.html" },
          { id: "stage1_anwar-al-anbiya_02", n: 2, day: 5, title: "من 35 إلى 61", file: "lectures/04.html" },
          { id: "stage1_anwar-al-anbiya_03", n: 3, day: 11, title: "من 63 إلى 93", file: "lectures/01.html" },
          { id: "stage1_anwar-al-anbiya_04", n: 4, day: 12, title: "من 95 إلى نهاية الكتاب", file: "lectures/02.html" }
        ]},
        { key: "riyad-al-saliheen", name: "شرح رياض الصالحين", sheikh: "غير محدد حاليًا", tags: ["المنهج_الإصلاحي", "التزكية", "علم_شرعي"], lectures: [
          { id: "stage1_riyad-al-saliheen_01", n: 1, day: 6, title: "باب الإخلاص والنية 1", file: "lectures/01.html" },
          { id: "stage1_riyad-al-saliheen_02", n: 2, day: 13, title: "باب الإخلاص والنية 2", file: "lectures/02.html" },
          { id: "stage1_riyad-al-saliheen_03", n: 3, day: 20, title: "باب التوبة 1", file: "lectures/03.html" },
          { id: "stage1_riyad-al-saliheen_04", n: 4, day: 27, title: "باب التوبة 1", file: "lectures/04.html" },
          { id: "stage1_riyad-al-saliheen_05", n: 5, day: 40, title: "باب التوبة 2", file: "lectures/05.html" },
          { id: "stage1_riyad-al-saliheen_06", n: 6, day: 41, title: "باب التوبة 3", file: "lectures/06.html" },
          { id: "stage1_riyad-al-saliheen_07", n: 7, day: 9, title: "باب الصبر 1", file: "lectures/07.html" },
          { id: "stage1_riyad-al-saliheen_08", n: 8, day: 10, title: "باب الصبر 2", file: "lectures/08.html" },
          { id: "stage1_riyad-al-saliheen_09", n: 9, day: 16, title: "باب الصبر 3", file: "lectures/09.html" },
          { id: "stage1_riyad-al-saliheen_10", n: 10, day: 24, title: "باب الصبر 4", file: "lectures/10.html" },
          { id: "stage1_riyad-al-saliheen_11", n: 11, day: 31, title: "باب الصبر 5", file: "lectures/11.html" },
          { id: "stage1_riyad-al-saliheen_12", n: 12, day: 37, title: "باب الصبر 6", file: "lectures/12.html" },
          { id: "stage1_riyad-al-saliheen_13", n: 13, day: 47, title: "باب الصدق", file: "lectures/13.html" },
          { id: "stage1_riyad-al-saliheen_14", n: 14, day: 55, title: "باب المراقبة 1", file: "lectures/14.html" },
          { id: "stage1_riyad-al-saliheen_15", n: 15, day: 62, title: "باب المراقبة 2", file: "lectures/15.html" },
          { id: "stage1_riyad-al-saliheen_16", n: 16, day: 69, title: "باب المراقبة 3", file: "lectures/16.html" }
        ]},
        { key: "sharaya-wasael-maqasid", name: "العلوم الشرعية بين الوسائل والمقاصد", sheikh: "أحمد السيد", tags: ["علم_شرعي", "تزكية"], lectures: [
          { id: "stage1_sharaya-wasael-maqasid_01", n: 1, day: 18, title: "محاضرة كاملة", file: "lectures/01.html" }
        ]},
        { key: "raqaeq-al-quran", name: "رقائق القرآن", sheikh: "إبراهيم السكران", tags: ["علم_شرعي", "تزكية"], lectures: [
          { id: "stage1_raqaeq-al-quran_01", n: 1, day: 19, title: "من البداية إلى ص 33", file: "lectures/01.html" },
          { id: "stage1_raqaeq-al-quran_02", n: 2, day: 25, title: "من 34 إلى 53", file: "lectures/02.html" },
          { id: "stage1_raqaeq-al-quran_03", n: 3, day: 26, title: "من 54 إلى 78", file: "lectures/03.html" },
          { id: "stage1_raqaeq-al-quran_04", n: 4, day: 30, title: "من 109 إلى 133", file: "lectures/04.html" },
          { id: "stage1_raqaeq-al-quran_05", n: 5, day: 31, title: "من 135 إلى النهاية", file: "lectures/05.html" }
        ]},
        { key: "mu_alajat-al-quran", name: "معالجة القرآن لنفوس المصلحين", sheikh: "أحمد السيد", tags: ["المنهج_الإصلاحي"], lectures: [
          { id: "stage1_mu_alajat-al-quran_01", n: 1, day: 35, title: "من بداية الكتاب إلى ص 31", file: "lectures/01.html" },
          { id: "stage1_mu_alajat-al-quran_02", n: 2, day: 36, title: "من 32 إلى ص 58", file: "lectures/02.html" },
          { id: "stage1_mu_alajat-al-quran_03", n: 3, day: 37, title: "من 59 إلى نهاية الكتاب", file: "lectures/03.html" }
        ]}
      ],
      days: [
        { day: 1, kind: "lecture", lectureId: "stage1_nahw_01", subjectKey: "nahw", subjectName: "مدخل إلى علم النحو", title: "محاضرة كاملة", link: "nahw/lectures/01.html" },
        { day: 2, kind: "lecture", lectureId: "stage1_fiqh_01", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 1", link: "fiqh/lectures/01.html" },
        { day: 3, kind: "lecture", lectureId: "stage1_fiqh_02", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 2", link: "fiqh/lectures/02.html" },
        { day: 4, kind: "lecture", lectureId: "stage1_anwar-al-anbiya_01", subjectKey: "anwar-al-anbiya", subjectName: "أنوار الأنبياء", title: "من بداية الكتاب إلى ص 34", link: "anwar-al-anbiya/lectures/03.html" },
        { day: 5, kind: "lecture", lectureId: "stage1_anwar-al-anbiya_02", subjectKey: "anwar-al-anbiya", subjectName: "أنوار الأنبياء", title: "من 35 إلى 61", link: "anwar-al-anbiya/lectures/04.html" },
        { day: 6, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_01", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الإخلاص والنية 1", link: "riyad-al-saliheen/lectures/01.html" },
        { day: 7, kind: "rest", id: "stage1_day_07", title: "استدراك وراحة" },
        { day: 8, kind: "lecture", lectureId: "stage1_fiqh_05", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 3", link: "fiqh/lectures/05.html" },
        { day: 9, kind: "lecture", lectureId: "stage1_fiqh_06", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 4", link: "fiqh/lectures/06.html" },
        { day: 10, kind: "lecture", lectureId: "stage1_fiqh_07", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 5", link: "fiqh/lectures/07.html" },
        { day: 11, kind: "lecture", lectureId: "stage1_anwar-al-anbiya_03", subjectKey: "anwar-al-anbiya", subjectName: "أنوار الأنبياء", title: "من 63 إلى 93", link: "anwar-al-anbiya/lectures/01.html" },
        { day: 12, kind: "lecture", lectureId: "stage1_anwar-al-anbiya_04", subjectKey: "anwar-al-anbiya", subjectName: "أنوار الأنبياء", title: "من 95 إلى نهاية الكتاب", link: "anwar-al-anbiya/lectures/02.html" },
        { day: 13, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_02", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الإخلاص والنية 2", link: "riyad-al-saliheen/lectures/02.html" },
        { day: 14, kind: "rest", id: "stage1_day_14", title: "استدراك وراحة" },
        { day: 15, kind: "lecture", lectureId: "stage1_fiqh_08", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 6", link: "fiqh/lectures/08.html" },
        { day: 16, kind: "lecture", lectureId: "stage1_fiqh_09", subjectKey: "fiqh", subjectName: "مدخل إلى علم الفقه", title: "المحاضرة 7", link: "fiqh/lectures/09.html" },
        { day: 17, kind: "lecture", lectureId: "stage1_quran-sciences_01_p1", subjectKey: "quran-sciences", subjectName: "مدخل إلى علوم القرآن", title: "المدخل إلى علوم القرآن والتفسير — الجزء الأول", link: "quran-sciences/lectures/01.html?p=1" },
        { day: 18, kind: "lecture", lectureId: "stage1_sharaya-wasael-maqasid_01", subjectKey: "sharaya-wasael-maqasid", subjectName: "العلوم الشرعية بين الوسائل والمقاصد", title: "محاضرة كاملة", link: "sharaya-wasael-maqasid/lectures/01.html" },
        { day: 19, kind: "lecture", lectureId: "stage1_raqaeq-al-quran_01", subjectKey: "raqaeq-al-quran", subjectName: "رقائق القرآن", title: "من البداية إلى ص 33", link: "raqaeq-al-quran/lectures/01.html" },
        { day: 20, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_03", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب التوبة 1", link: "riyad-al-saliheen/lectures/03.html" },
        { day: 21, kind: "rest", id: "stage1_day_21", title: "استدراك وراحة" },
        { day: 22, kind: "lecture", lectureId: "stage1_quran-sciences_01_p2", subjectKey: "quran-sciences", subjectName: "مدخل إلى علوم القرآن", title: "المدخل إلى علوم القرآن والتفسير — الجزء الثاني", link: "quran-sciences/lectures/01.html?p=2" },
        { day: 23, kind: "lecture", lectureId: "stage1_aqeedah_01", subjectKey: "aqeedah", subjectName: "مدخل إلى علم العقيدة", title: "محاضرة كاملة (١)", link: "aqeedah/lectures/01.html" },
        { day: 24, kind: "lecture", lectureId: "stage1_aqeedah_01", subjectKey: "aqeedah", subjectName: "مدخل إلى علم العقيدة", title: "محاضرة كاملة (٢)", link: "aqeedah/lectures/01.html" },
        { day: 25, kind: "lecture", lectureId: "stage1_raqaeq-al-quran_02", subjectKey: "raqaeq-al-quran", subjectName: "رقائق القرآن", title: "من 34 إلى 53", link: "raqaeq-al-quran/lectures/02.html" },
        { day: 26, kind: "lecture", lectureId: "stage1_raqaeq-al-quran_03", subjectKey: "raqaeq-al-quran", subjectName: "رقائق القرآن", title: "من 54 إلى 78", link: "raqaeq-al-quran/lectures/03.html" },
        { day: 27, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_04", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب التوبة 1", link: "riyad-al-saliheen/lectures/04.html" },
        { day: 28, kind: "rest", id: "stage1_day_28", title: "استدراك وراحة" },
        { day: 29, kind: "lecture", lectureId: "stage1_hadith_01", subjectKey: "hadith", subjectName: "مدخل إلى علم الحديث", title: "المجلس الأول (1/3)", link: "hadith/lectures/01.html?p=stage1_hadith_01" },
        { day: 30, kind: "lecture", lectureId: "stage1_raqaeq-al-quran_04", subjectKey: "raqaeq-al-quran", subjectName: "رقائق القرآن", title: "من 109 إلى 133", link: "raqaeq-al-quran/lectures/04.html" },
        { day: 31, kind: "lecture", lectureId: "stage1_raqaeq-al-quran_05", subjectKey: "raqaeq-al-quran", subjectName: "رقائق القرآن", title: "من 135 إلى النهاية", link: "raqaeq-al-quran/lectures/05.html" },
        { day: 32, kind: "lecture", lectureId: "stage1_hadith_02", subjectKey: "hadith", subjectName: "مدخل إلى علم الحديث", title: "المجلس الأول (2/3)", link: "hadith/lectures/01.html?p=stage1_hadith_02" },
        { day: 33, kind: "lecture", lectureId: "stage1_hadith_03", subjectKey: "hadith", subjectName: "مدخل إلى علم الحديث", title: "المجلس الأول (3/3)", link: "hadith/lectures/01.html?p=stage1_hadith_03" },
        { day: 34, kind: "lecture", lectureId: "stage1_hadith_04", subjectKey: "hadith", subjectName: "مدخل إلى علم الحديث", title: "المجلس الثاني (1/2)", link: "hadith/lectures/02.html?p=stage1_hadith_04" },
        { day: 35, kind: "lecture", lectureId: "stage1_mu_alajat-al-quran_01", subjectKey: "mu_alajat-al-quran", subjectName: "معالجة القرآن لنفوس المصلحين", title: "من بداية الكتاب إلى ص 31", link: "mu_alajat-al-quran/lectures/01.html" },
        { day: 36, kind: "lecture", lectureId: "stage1_mu_alajat-al-quran_02", subjectKey: "mu_alajat-al-quran", subjectName: "معالجة القرآن لنفوس المصلحين", title: "من 32 إلى ص 58", link: "mu_alajat-al-quran/lectures/02.html" },
        { day: 37, kind: "lecture", lectureId: "stage1_mu_alajat-al-quran_03", subjectKey: "mu_alajat-al-quran", subjectName: "معالجة القرآن لنفوس المصلحين", title: "من 59 إلى نهاية الكتاب", link: "mu_alajat-al-quran/lectures/03.html" },
        { day: 38, kind: "rest", id: "stage1_day_38", title: "استدراك وراحة" },
        { day: 39, kind: "lecture", lectureId: "stage1_hadith_05", subjectKey: "hadith", subjectName: "مدخل إلى علم الحديث", title: "المجلس الثاني (2/2)", link: "hadith/lectures/02.html?p=stage1_hadith_05" },
        { day: 40, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_05", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب التوبة 2", link: "riyad-al-saliheen/lectures/05.html" },
        { day: 41, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_06", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب التوبة 3", link: "riyad-al-saliheen/lectures/06.html" },
        { day: 42, kind: "rest", id: "stage1_day_42", title: "استدراك وراحة" },
        { day: 43, kind: "rest", id: "stage1_day_43", title: "استدراك وراحة" },
        { day: 44, kind: "rest", id: "stage1_day_44", title: "استدراك وراحة" },
        { day: 45, kind: "rest", id: "stage1_day_45", title: "استدراك وراحة" },
        { day: 46, kind: "rest", id: "stage1_day_46", title: "استدراك وراحة" },
        { day: 47, kind: "rest", id: "stage1_day_47", title: "استدراك وراحة" },
        { day: 48, kind: "exam", id: "stage1_day_48", title: "اختبار المرحلة" }
      ],
      totalLectures: 45
    },
    stage2: {
      id: "stage2",
      name: "المرحلة الثانية",
      subjects: [
        { key: "aqeedah2", name: "الحقيبة الشرعية (العقيدة)", sheikh: "أحمد السيد", tags: ["علم_شرعي", "عقيدة"], lectures: [
          { id: "stage2_aqeedah2_01", n: 1, day: 1, title: "الحقيبة الشرعية (العقيدة) 1", file: "lectures/01.html" },
          { id: "stage2_aqeedah2_02", n: 2, day: 2, title: "الحقيبة الشرعية (العقيدة) 2", file: "lectures/02.html" },
          { id: "stage2_aqeedah2_03", n: 3, day: 3, title: "الحقيبة الشرعية (العقيدة) 3", file: "lectures/03.html" },
          { id: "stage2_aqeedah2_04", n: 4, day: 5, title: "الحقيبة الشرعية (العقيدة) 4", file: "lectures/04.html" },
          { id: "stage2_aqeedah2_05", n: 5, day: 6, title: "الحقيبة الشرعية (العقيدة) 5، 6", file: "lectures/05.html" },
          { id: "stage2_aqeedah2_06", n: 6, day: 7, title: "الحقيبة الشرعية (العقيدة) 7، 8", file: "lectures/06.html" },
          { id: "stage2_aqeedah2_07", n: 7, day: 12, title: "الحقيبة الشرعية (العقيدة) 9", file: "lectures/07.html" },
          { id: "stage2_aqeedah2_08", n: 8, day: 13, title: "الحقيبة الشرعية (العقيدة) 10", file: "lectures/08.html" },
          { id: "stage2_aqeedah2_09", n: 9, day: 14, title: "الحقيبة الشرعية (العقيدة) 11", file: "lectures/09.html" },
          { id: "stage2_aqeedah2_10", n: 10, day: 19, title: "الحقيبة الشرعية (العقيدة) 12 — النصف الأول", file: "lectures/10.html" },
          { id: "stage2_aqeedah2_11", n: 11, day: 20, title: "الحقيبة الشرعية (العقيدة) 12 — النصف الثاني", file: "lectures/11.html" },
          { id: "stage2_aqeedah2_12", n: 12, day: 21, title: "الحقيبة الشرعية (العقيدة) 13", file: "lectures/12.html" },
          { id: "stage2_aqeedah2_13", n: 13, day: 26, title: "الحقيبة الشرعية (العقيدة) 14", file: "lectures/13.html" },
          { id: "stage2_aqeedah2_14", n: 14, day: 27, title: "الحقيبة الشرعية (العقيدة) 15", file: "lectures/14.html" }
        ]},
        { key: "mushawwiq", name: "المشوّق إلى القرآن", sheikh: "عمر الشرقاوي", tags: ["تزكية"], lectures: [
          { id: "stage2_mushawwiq_01", n: 1, day: 8, title: "المشوق إلى القرآن — من ص 9 إلى 41", file: "lectures/01.html" },
          { id: "stage2_mushawwiq_02", n: 2, day: 9, title: "المشوق إلى القرآن — من ص 43 إلى 66", file: "lectures/02.html" },
          { id: "stage2_mushawwiq_03", n: 3, day: 10, title: "المشوق إلى القرآن — من ص 67 إلى 93", file: "lectures/03.html" },
          { id: "stage2_mushawwiq_04", n: 4, day: 15, title: "المشوق إلى القرآن — من ص 95 إلى 131", file: "lectures/04.html" },
          { id: "stage2_mushawwiq_05", n: 5, day: 16, title: "المشوق إلى القرآن — من ص 133 إلى 160", file: "lectures/05.html" },
          { id: "stage2_mushawwiq_06", n: 6, day: 17, title: "المشوق إلى القرآن — من ص 161 إلى 187", file: "lectures/06.html" },
          { id: "stage2_mushawwiq_07", n: 7, day: 22, title: "المشوق إلى القرآن — من ص 189 إلى نهاية الكتاب", file: "lectures/07.html" }
        ]},
        { key: "adhkar", name: "معاني الأذكار", sheikh: "محمد صالح المنجد", tags: ["تزكية"], lectures: [
          { id: "stage2_adhkar_01", n: 1, day: 23, title: "معاني الأذكار — من ص 7 إلى ص 32", file: "lectures/01.html" },
          { id: "stage2_adhkar_02", n: 2, day: 24, title: "معاني الأذكار — من ص 33 إلى ص 70", file: "lectures/02.html" },
          { id: "stage2_adhkar_03", n: 3, day: 28, title: "معاني الأذكار — من ص 71 إلى ص 114", file: "lectures/03.html" },
          { id: "stage2_adhkar_04", n: 4, day: 29, title: "معاني الأذكار — من ص 115 إلى ص 153", file: "lectures/04.html" },
          { id: "stage2_adhkar_05", n: 5, day: 30, title: "معاني الأذكار — من ص 154 إلى نهاية الكتاب", file: "lectures/05.html" }
        ]},
        { key: "hosul-tolab", name: "حصول الطلب بسلوك الأدب", sheikh: "محمد الشريف", tags: ["تزكية", "علم_شرعي", "عقيدة"], lectures: [
          { id: "stage2_hosul-tolab_01", n: 1, day: 31, title: "حصول الطلب بسلوك الأدب — من ص 9 إلى ص 43", file: "lectures/01.html" },
          { id: "stage2_hosul-tolab_02", n: 2, day: 32, title: "حصول الطلب بسلوك الأدب — من ص 44 إلى 71", file: "lectures/02.html" },
          { id: "stage2_hosul-tolab_03", n: 3, day: 33, title: "حصول الطلب بسلوك الأدب — من ص 72 إلى 110", file: "lectures/03.html" },
          { id: "stage2_hosul-tolab_04", n: 4, day: 34, title: "حصول الطلب بسلوك الأدب — من ص 111 إلى نهاية الكتاب", file: "lectures/04.html" }
        ]},
        { key: "mahasin-islam", name: "محاسن الإسلام", sheikh: "أحمد السيد", tags: ["تزكية"], lectures: [
          { id: "stage2_mahasin-islam_01", n: 1, day: 35, title: "محاسن الإسلام — من ص 7 إلى 35", file: "lectures/01.html" },
          { id: "stage2_mahasin-islam_02", n: 2, day: 36, title: "محاسن الإسلام — من ص 36 إلى نهاية الكتاب", file: "lectures/02.html" }
        ]},
        { key: "rakiza-tafsir", name: "شرح الركيزة في أصول التفسير", sheikh: "محمد الخضيري", tags: ["علم_شرعي", "علم_قرآن"], lectures: [
          { id: "stage2_rakiza-tafsir_01", n: 1, day: 43, title: "شرح الركيزة في أصول التفسير — محاضرة 1", file: "lectures/01.html" },
          { id: "stage2_rakiza-tafsir_02", n: 2, day: 44, title: "شرح الركيزة في أصول التفسير — محاضرة 2", file: "lectures/02.html" },
          { id: "stage2_rakiza-tafsir_03", n: 3, day: 45, title: "شرح الركيزة في أصول التفسير — محاضرة 3", file: "lectures/03.html" },
          { id: "stage2_rakiza-tafsir_04", n: 4, day: 50, title: "شرح الركيزة في أصول التفسير — محاضرة 4", file: "lectures/04.html" },
          { id: "stage2_rakiza-tafsir_05", n: 5, day: 51, title: "شرح الركيزة في أصول التفسير — محاضرة 5", file: "lectures/05.html" }
        ]},
        { key: "sawiyat-al-mumin", name: "سَوِيّة المؤمن", sheikh: "أحمد السيد", tags: ["تزكية"], lectures: [
          { id: "stage2_sawiyat-al-mumin_01", n: 1, day: 46, title: "سَوِيّة المؤمن: الثبات 1", file: "lectures/01.html" },
          { id: "stage2_sawiyat-al-mumin_02", n: 2, day: 47, title: "سَوِيّة المؤمن: الثبات 2", file: "lectures/02.html" },
          { id: "stage2_sawiyat-al-mumin_03", n: 3, day: 48, title: "سَوِيّة المؤمن: قوة النفس", file: "lectures/03.html" },
          { id: "stage2_sawiyat-al-mumin_04", n: 4, day: 52, title: "سَوِيّة المؤمن: التفاؤل", file: "lectures/04.html" }
        ]},
        { key: "qawaid-nabawiya", name: "قواعد نبوية", sheikh: "عمر المقبل", tags: ["تزكية"], lectures: [
          { id: "stage2_qawaid-nabawiya_01", n: 1, day: 53, title: "قواعد نبوية — من ص 11 إلى ص 37", file: "lectures/01.html" },
          { id: "stage2_qawaid-nabawiya_02", n: 2, day: 54, title: "قواعد نبوية — من ص 38 إلى ص 68", file: "lectures/02.html" },
          { id: "stage2_qawaid-nabawiya_03", n: 3, day: 55, title: "قواعد نبوية — من ص 69 إلى ص 98", file: "lectures/03.html" },
          { id: "stage2_qawaid-nabawiya_04", n: 4, day: 60, title: "قواعد نبوية — من ص 99 إلى ص 129", file: "lectures/04.html" },
          { id: "stage2_qawaid-nabawiya_05", n: 5, day: 61, title: "قواعد نبوية — من ص 130 إلى ص 159", file: "lectures/05.html" },
          { id: "stage2_qawaid-nabawiya_06", n: 6, day: 62, title: "قواعد نبوية — من ص 160 إلى ص 189", file: "lectures/06.html" },
          { id: "stage2_qawaid-nabawiya_07", n: 7, day: 67, title: "قواعد نبوية — من ص 190 إلى ص 222", file: "lectures/07.html" },
          { id: "stage2_qawaid-nabawiya_08", n: 8, day: 68, title: "قواعد نبوية — من ص 223 إلى ص 250", file: "lectures/08.html" },
          { id: "stage2_qawaid-nabawiya_09", n: 9, day: 69, title: "قواعد نبوية — من ص 251 إلى ص 285", file: "lectures/09.html" },
          { id: "stage2_qawaid-nabawiya_10", n: 10, day: 74, title: "قواعد نبوية — من ص 286 إلى ص 318", file: "lectures/10.html" },
          { id: "stage2_qawaid-nabawiya_11", n: 11, day: 75, title: "قواعد نبوية — من ص 319 إلى نهاية الكتاب", file: "lectures/11.html" }
        ]},
        { key: "dalil-quran", name: "الدليل إلى القرآن", sheikh: "عمرو الشرقاوي", tags: ["علم_شرعي", "علوم_القرآن"], lectures: [
          { id: "stage2_dalil-quran_01", n: 1, day: 57, title: "الدليل إلى القرآن — من ص 9 إلى 34", file: "lectures/01.html" },
          { id: "stage2_dalil-quran_02", n: 2, day: 58, title: "الدليل إلى القرآن — من ص 35 إلى 57", file: "lectures/02.html" },
          { id: "stage2_dalil-quran_03", n: 3, day: 59, title: "الدليل إلى القرآن — من ص 58 إلى 84", file: "lectures/03.html" },
          { id: "stage2_dalil-quran_04", n: 4, day: 64, title: "الدليل إلى القرآن — من ص 85 إلى 107", file: "lectures/04.html" },
          { id: "stage2_dalil-quran_05", n: 5, day: 65, title: "الدليل إلى القرآن — من ص 108 إلى 135", file: "lectures/05.html" },
          { id: "stage2_dalil-quran_06", n: 6, day: 66, title: "الدليل إلى القرآن — من ص 137 إلى 156", file: "lectures/06.html" },
          { id: "stage2_dalil-quran_07", n: 7, day: 71, title: "الدليل إلى القرآن — من ص 158 إلى 187", file: "lectures/07.html" },
          { id: "stage2_dalil-quran_08", n: 8, day: 72, title: "الدليل إلى القرآن — من ص 188 إلى 219", file: "lectures/08.html" },
          { id: "stage2_dalil-quran_09", n: 9, day: 73, title: "الدليل إلى القرآن — من ص 220 إلى نهاية الكتاب", file: "lectures/09.html" }
        ]}
      ],
      days: [
        { day: 1, kind: "lecture", lectureId: "stage2_aqeedah2_01", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 1", link: "aqeedah2/lectures/01.html" },
        { day: 2, kind: "lecture", lectureId: "stage2_aqeedah2_02", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 2", link: "aqeedah2/lectures/02.html" },
        { day: 3, kind: "lecture", lectureId: "stage2_aqeedah2_03", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 3", link: "aqeedah2/lectures/03.html" },
        { day: 4, kind: "rest", id: "stage2_day_04", title: "استدراك وراحة" },
        { day: 5, kind: "lecture", lectureId: "stage2_aqeedah2_04", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 4", link: "aqeedah2/lectures/04.html" },
        { day: 6, kind: "lecture", lectureId: "stage2_aqeedah2_05", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 5، 6", link: "aqeedah2/lectures/05.html" },
        { day: 7, kind: "lecture", lectureId: "stage2_aqeedah2_06", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 7، 8", link: "aqeedah2/lectures/06.html" },
        { day: 8, kind: "lecture", lectureId: "stage2_mushawwiq_01", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 9 إلى 41", link: "mushawwiq/lectures/01.html" },
        { day: 9, kind: "lecture", lectureId: "stage2_mushawwiq_02", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 43 إلى 66", link: "mushawwiq/lectures/02.html" },
        { day: 9, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_07", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 1", link: "riyad-al-saliheen/lectures/07.html" },
        { day: 10, kind: "lecture", lectureId: "stage2_mushawwiq_03", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 67 إلى 93", link: "mushawwiq/lectures/03.html" },
        { day: 10, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_08", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 2", link: "riyad-al-saliheen/lectures/08.html" },
        { day: 11, kind: "rest", id: "stage2_day_11", title: "استدراك وراحة" },
        { day: 12, kind: "lecture", lectureId: "stage2_aqeedah2_07", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 9", link: "aqeedah2/lectures/07.html" },
        { day: 13, kind: "lecture", lectureId: "stage2_aqeedah2_08", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 10", link: "aqeedah2/lectures/08.html" },
        { day: 14, kind: "lecture", lectureId: "stage2_aqeedah2_09", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 11", link: "aqeedah2/lectures/09.html" },
        { day: 15, kind: "lecture", lectureId: "stage2_mushawwiq_04", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 95 إلى 131", link: "mushawwiq/lectures/04.html" },
        { day: 16, kind: "lecture", lectureId: "stage2_mushawwiq_05", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 133 إلى 160", link: "mushawwiq/lectures/05.html" },
        { day: 16, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_09", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 3", link: "riyad-al-saliheen/lectures/09.html" },
        { day: 17, kind: "lecture", lectureId: "stage2_mushawwiq_06", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 161 إلى 187", link: "mushawwiq/lectures/06.html" },
        { day: 18, kind: "rest", id: "stage2_day_18", title: "استدراك وراحة" },
        { day: 19, kind: "lecture", lectureId: "stage2_aqeedah2_10", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 12 — النصف الأول", link: "aqeedah2/lectures/10.html" },
        { day: 20, kind: "lecture", lectureId: "stage2_aqeedah2_11", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 12 — النصف الثاني", link: "aqeedah2/lectures/11.html" },
        { day: 21, kind: "lecture", lectureId: "stage2_aqeedah2_12", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 13", link: "aqeedah2/lectures/12.html" },
        { day: 22, kind: "lecture", lectureId: "stage2_mushawwiq_07", subjectKey: "mushawwiq", subjectName: "المشوّق إلى القرآن", title: "المشوق إلى القرآن — من ص 189 إلى نهاية الكتاب", link: "mushawwiq/lectures/07.html" },
        { day: 23, kind: "lecture", lectureId: "stage2_adhkar_01", subjectKey: "adhkar", subjectName: "معاني الأذكار", title: "معاني الأذكار — من ص 7 إلى ص 32", link: "adhkar/lectures/01.html" },
        { day: 24, kind: "lecture", lectureId: "stage2_adhkar_02", subjectKey: "adhkar", subjectName: "معاني الأذكار", title: "معاني الأذكار — من ص 33 إلى ص 70", link: "adhkar/lectures/02.html" },
        { day: 24, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_10", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 4", link: "riyad-al-saliheen/lectures/10.html" },
        { day: 25, kind: "rest", id: "stage2_day_25", title: "استدراك وراحة" },
        { day: 26, kind: "lecture", lectureId: "stage2_aqeedah2_13", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 14", link: "aqeedah2/lectures/13.html" },
        { day: 27, kind: "lecture", lectureId: "stage2_aqeedah2_14", subjectKey: "aqeedah2", subjectName: "الحقيبة الشرعية (العقيدة)", title: "الحقيبة الشرعية (العقيدة) 15", link: "aqeedah2/lectures/14.html" },
        { day: 28, kind: "lecture", lectureId: "stage2_adhkar_03", subjectKey: "adhkar", subjectName: "معاني الأذكار", title: "معاني الأذكار — من ص 71 إلى ص 114", link: "adhkar/lectures/03.html" },
        { day: 29, kind: "lecture", lectureId: "stage2_adhkar_04", subjectKey: "adhkar", subjectName: "معاني الأذكار", title: "معاني الأذكار — من ص 115 إلى ص 153", link: "adhkar/lectures/04.html" },
        { day: 30, kind: "lecture", lectureId: "stage2_adhkar_05", subjectKey: "adhkar", subjectName: "معاني الأذكار", title: "معاني الأذكار — من ص 154 إلى نهاية الكتاب", link: "adhkar/lectures/05.html" },
        { day: 31, kind: "lecture", lectureId: "stage2_hosul-tolab_01", subjectKey: "hosul-tolab", subjectName: "حصول الطلب بسلوك الأدب", title: "حصول الطلب بسلوك الأدب — من ص 9 إلى ص 43", link: "hosul-tolab/lectures/01.html" },
        { day: 31, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_11", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 5", link: "riyad-al-saliheen/lectures/11.html" },
        { day: 32, kind: "lecture", lectureId: "stage2_hosul-tolab_02", subjectKey: "hosul-tolab", subjectName: "حصول الطلب بسلوك الأدب", title: "حصول الطلب بسلوك الأدب — من ص 44 إلى 71", link: "hosul-tolab/lectures/02.html" },
        { day: 33, kind: "lecture", lectureId: "stage2_hosul-tolab_03", subjectKey: "hosul-tolab", subjectName: "حصول الطلب بسلوك الأدب", title: "حصول الطلب بسلوك الأدب — من ص 72 إلى 110", link: "hosul-tolab/lectures/03.html" },
        { day: 34, kind: "lecture", lectureId: "stage2_hosul-tolab_04", subjectKey: "hosul-tolab", subjectName: "حصول الطلب بسلوك الأدب", title: "حصول الطلب بسلوك الأدب — من ص 111 إلى نهاية الكتاب", link: "hosul-tolab/lectures/04.html" },
        { day: 35, kind: "lecture", lectureId: "stage2_mahasin-islam_01", subjectKey: "mahasin-islam", subjectName: "محاسن الإسلام", title: "محاسن الإسلام — من ص 7 إلى 35", link: "mahasin-islam/lectures/01.html" },
        { day: 36, kind: "lecture", lectureId: "stage2_mahasin-islam_02", subjectKey: "mahasin-islam", subjectName: "محاسن الإسلام", title: "محاسن الإسلام — من ص 36 إلى نهاية الكتاب", link: "mahasin-islam/lectures/02.html" },
        { day: 37, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_12", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصبر 6", link: "riyad-al-saliheen/lectures/12.html" },
        { day: 38, kind: "rest", id: "stage2_day_38", title: "استدراك وراحة" },
        { day: 39, kind: "rest", id: "stage2_day_39", title: "استدراك وراحة" },
        { day: 40, kind: "rest", id: "stage2_day_40", title: "استدراك وراحة" },
        { day: 41, kind: "exam", id: "stage2_day_41", title: "الاختبار النصفي الأول للمرحلة الثانية" },
        { day: 42, kind: "exam", id: "stage2_day_42", title: "الاختبار النصفي الثاني للمرحلة الثانية" },
        { day: 43, kind: "lecture", lectureId: "stage2_rakiza-tafsir_01", subjectKey: "rakiza-tafsir", subjectName: "شرح الركيزة في أصول التفسير", title: "شرح الركيزة في أصول التفسير — محاضرة 1", link: "rakiza-tafsir/lectures/01.html" },
        { day: 44, kind: "lecture", lectureId: "stage2_rakiza-tafsir_02", subjectKey: "rakiza-tafsir", subjectName: "شرح الركيزة في أصول التفسير", title: "شرح الركيزة في أصول التفسير — محاضرة 2", link: "rakiza-tafsir/lectures/02.html" },
        { day: 45, kind: "lecture", lectureId: "stage2_rakiza-tafsir_03", subjectKey: "rakiza-tafsir", subjectName: "شرح الركيزة في أصول التفسير", title: "شرح الركيزة في أصول التفسير — محاضرة 3", link: "rakiza-tafsir/lectures/03.html" },
        { day: 46, kind: "lecture", lectureId: "stage2_sawiyat-al-mumin_01", subjectKey: "sawiyat-al-mumin", subjectName: "سَوِيّة المؤمن", title: "سَوِيّة المؤمن: الثبات 1", link: "sawiyat-al-mumin/lectures/01.html" },
        { day: 47, kind: "lecture", lectureId: "stage2_sawiyat-al-mumin_02", subjectKey: "sawiyat-al-mumin", subjectName: "سَوِيّة المؤمن", title: "سَوِيّة المؤمن: الثبات 2", link: "sawiyat-al-mumin/lectures/02.html" },
        { day: 47, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_13", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب الصدق", link: "riyad-al-saliheen/lectures/13.html" },
        { day: 48, kind: "lecture", lectureId: "stage2_sawiyat-al-mumin_03", subjectKey: "sawiyat-al-mumin", subjectName: "سَوِيّة المؤمن", title: "سَوِيّة المؤمن: قوة النفس", link: "sawiyat-al-mumin/lectures/03.html" },
        { day: 49, kind: "rest", id: "stage2_day_49", title: "استدراك وراحة" },
        { day: 50, kind: "lecture", lectureId: "stage2_rakiza-tafsir_04", subjectKey: "rakiza-tafsir", subjectName: "شرح الركيزة في أصول التفسير", title: "شرح الركيزة في أصول التفسير — محاضرة 4", link: "rakiza-tafsir/lectures/04.html" },
        { day: 51, kind: "lecture", lectureId: "stage2_rakiza-tafsir_05", subjectKey: "rakiza-tafsir", subjectName: "شرح الركيزة في أصول التفسير", title: "شرح الركيزة في أصول التفسير — محاضرة 5", link: "rakiza-tafsir/lectures/05.html" },
        { day: 52, kind: "lecture", lectureId: "stage2_sawiyat-al-mumin_04", subjectKey: "sawiyat-al-mumin", subjectName: "سَوِيّة المؤمن", title: "سَوِيّة المؤمن: التفاؤل", link: "sawiyat-al-mumin/lectures/04.html" },
        { day: 53, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_01", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 11 إلى ص 37", link: "qawaid-nabawiya/lectures/01.html" },
        { day: 54, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_02", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 38 إلى ص 68", link: "qawaid-nabawiya/lectures/02.html" },
        { day: 55, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_03", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 69 إلى ص 98", link: "qawaid-nabawiya/lectures/03.html" },
        { day: 55, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_14", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب المراقبة 1", link: "riyad-al-saliheen/lectures/14.html" },
        { day: 56, kind: "rest", id: "stage2_day_56", title: "استدراك وراحة" },
        { day: 57, kind: "lecture", lectureId: "stage2_dalil-quran_01", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 9 إلى 34", link: "dalil-quran/lectures/01.html" },
        { day: 58, kind: "lecture", lectureId: "stage2_dalil-quran_02", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 35 إلى 57", link: "dalil-quran/lectures/02.html" },
        { day: 59, kind: "lecture", lectureId: "stage2_dalil-quran_03", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 58 إلى 84", link: "dalil-quran/lectures/03.html" },
        { day: 60, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_04", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 99 إلى ص 129", link: "qawaid-nabawiya/lectures/04.html" },
        { day: 61, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_05", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 130 إلى ص 159", link: "qawaid-nabawiya/lectures/05.html" },
        { day: 62, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_06", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 160 إلى ص 189", link: "qawaid-nabawiya/lectures/06.html" },
        { day: 62, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_15", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب المراقبة 2", link: "riyad-al-saliheen/lectures/15.html" },
        { day: 63, kind: "rest", id: "stage2_day_63", title: "استدراك وراحة" },
        { day: 64, kind: "lecture", lectureId: "stage2_dalil-quran_04", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 85 إلى 107", link: "dalil-quran/lectures/04.html" },
        { day: 65, kind: "lecture", lectureId: "stage2_dalil-quran_05", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 108 إلى 135", link: "dalil-quran/lectures/05.html" },
        { day: 66, kind: "lecture", lectureId: "stage2_dalil-quran_06", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 137 إلى 156", link: "dalil-quran/lectures/06.html" },
        { day: 67, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_07", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 190 إلى ص 222", link: "qawaid-nabawiya/lectures/07.html" },
        { day: 68, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_08", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 223 إلى ص 250", link: "qawaid-nabawiya/lectures/08.html" },
        { day: 69, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_09", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 251 إلى ص 285", link: "qawaid-nabawiya/lectures/09.html" },
        { day: 69, kind: "lecture", lectureId: "stage1_riyad-al-saliheen_16", subjectKey: "riyad-al-saliheen", subjectName: "شرح رياض الصالحين", title: "باب المراقبة 3", link: "riyad-al-saliheen/lectures/16.html" },
        { day: 70, kind: "rest", id: "stage2_day_70", title: "استدراك وراحة" },
        { day: 71, kind: "lecture", lectureId: "stage2_dalil-quran_07", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 158 إلى 187", link: "dalil-quran/lectures/07.html" },
        { day: 72, kind: "lecture", lectureId: "stage2_dalil-quran_08", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 188 إلى 219", link: "dalil-quran/lectures/08.html" },
        { day: 73, kind: "lecture", lectureId: "stage2_dalil-quran_09", subjectKey: "dalil-quran", subjectName: "الدليل إلى القرآن", title: "الدليل إلى القرآن — من ص 220 إلى نهاية الكتاب", link: "dalil-quran/lectures/09.html" },
        { day: 74, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_10", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 286 إلى ص 318", link: "qawaid-nabawiya/lectures/10.html" },
        { day: 75, kind: "lecture", lectureId: "stage2_qawaid-nabawiya_11", subjectKey: "qawaid-nabawiya", subjectName: "قواعد نبوية", title: "قواعد نبوية — من ص 319 إلى نهاية الكتاب", link: "qawaid-nabawiya/lectures/11.html" },
        { day: 76, kind: "rest", id: "stage2_day_76", title: "استدراك وراحة" },
        { day: 77, kind: "rest", id: "stage2_day_77", title: "استدراك وراحة" },
        { day: 78, kind: "rest", id: "stage2_day_78", title: "استدراك وراحة" },
        { day: 79, kind: "exam", id: "stage2_day_79", title: "الامتحان الأول على النصف الثاني للمرحلة الثانية" },
        { day: 80, kind: "exam", id: "stage2_day_80", title: "الامتحان الثاني على النصف الثاني للمرحلة الثانية" },
        { day: 81, kind: "exam", id: "stage2_day_81", title: "الامتحان النهائي على المرحلة الثانية" }
      ],
      totalLectures: 61
    },
  }
};
